:workstation-pe:M::MZ::/usr/local/bin/workstation-winexec:
:workstation-msi:E::msi::/usr/local/bin/workstation-winexec:
:workstation-msi-upper:E::MSI::/usr/local/bin/workstation-winexec:
:workstation-bat:E::bat::/usr/local/bin/workstation-winexec:
:workstation-bat-upper:E::BAT::/usr/local/bin/workstation-winexec:
:workstation-cmd:E::cmd::/usr/local/bin/workstation-winexec:
:workstation-cmd-upper:E::CMD::/usr/local/bin/workstation-winexec:
:workstation-com:E::com::/usr/local/bin/workstation-winexec:
:workstation-com-upper:E::COM::/usr/local/bin/workstation-winexec:
:workstation-pif:E::pif::/usr/local/bin/workstation-winexec:
:workstation-pif-upper:E::PIF::/usr/local/bin/workstation-winexec:
:workstation-reg:E::reg::/usr/local/bin/workstation-winexec:
:workstation-reg-upper:E::REG::/usr/local/bin/workstation-winexec:
